version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:4000
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb+srv://root:forTestUsers@usersservice.xx37e.mongodb.net/user-service
      - JWT_SECRET=myjwtsecret
    command: npm run start:prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge